# Используем базовый образ Node.js
FROM node:latest

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /node-js

# Копируем package.json и package-lock.json и устанавливаем зависимости
COPY package*.json ./
RUN npm install

# Копируем исходный код приложения
COPY . .

# Определяем порт, на котором будет работать приложение Node.js
EXPOSE 2021

# Команда для запуска приложения
CMD ["npm", "start"]
