name: CI

on:
  push:
    branches: [ final ]

jobs:
  build:
    runs-on: self-hosted
    env:
      PASSWORD: ${{ secrets.CI_REGISTRY_PASSWORD }}
    steps:
    - name: Login to Docker Hub
      run: echo -e "112211\nPassword1" | sudo -S docker login -u "tvoilex" --password-stdin docker.io
    - name: Docker Image build
      run: cd /home/nodejs/server/node-js && echo 112211 | sudo -S docker-compose build
    - name: test
      run:  echo ${{ github.sha }}
    - name: Docker Tag
      run: echo 112211 | sudo -S docker tag node-js_nodejs_app:latest docker.io/tvoilex/nodejs:${{ github.sha }}
    - name: Push to Docker Hub
      run: echo 112211 | sudo -S docker push docker.io/tvoilex/nodejs:${{ github.sha }}
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Docker Pull
      run: echo 112211 | sudo -S docker pull docker.io/tvoilex/nodejs:${{ github.sha }}
    - name: Docker build 
      run: cd /home/nodejs/server/node-js && echo 112211 | sudo -S docker-compose build --pull && echo 112211 | sudo -S docker-compose down && sudo docker-compose up -d

