name: CI

on:
  push:
    branches: [ final ]

jobs:
  build:
    runs-on: self-hosted
    env:
      PASSWORD: ${{ secrets.CI_REGISTRY_PASSWORD }}
    steps:
    - name: Login to Docker Hub
      run: echo $PASSWORD | sudo docker login -u "tvoilex" --password-stdin docker.io
