name: CI

on:
  push:
    branches: [ final ]

jobs:
  build:
    runs-on: self-hosted
    env:
      PASSWORD: ${{ secrets.CI_REGISTRY_PASSWORD }}
    steps:
    - name: Login to Docker Hub
      run: echo $PASSWORD | sudo docker login -u "tvoilex" --password-stdin docker.io
    - name: Docker Image build
      run: cd /home/nodejs/server/node-js && docker-compose build
    - name: Docker Tag
      run: docker tag node-js_nodejs_app docker.io/tvoilex/nodejs:{{ github.sha }}
    - name: Push to Docker Hub
      run: docker push docker.io/tvoilex/nodejs:{{ github.sha }}


